name: Pull Request Opened

on:
  pull_request:
    branches:
      - 'main'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.1.2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build report
      run: |
        mkdir coverage
        echo `date` >coverage/index.html
        echo "Need to create report for pull request"
        pull_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        echo "Pull request number is $pull_number"

    - name: Archive report
      uses: actions/upload-artifact@v2
      with:
        name: generated-report
        path: coverage
