name: Continuous Integration

on:
  pull_request:
    branches-ignore:
      - 'main'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.1.2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build report
      run: |
        mkdir coverage
        echo `date` >coverage/index.html

    - name: Archive report
      uses: actions/upload-artifact@v2
      with:
        name: generated-report
        path: coverage
